# Generated by Django 6.1 on 2026-08-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.JSONField(default=dict),
        ),
    ]
